<?php
return [
    [
        'name' => 'Visual Studio Code',
        'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png',
        'description' => 'Editor di codice open source',
        'category' => 'Editor di codice',
        'release_year' => 2015,
        'latest_version' => '1.63.2',
        'download_link' => 'https://code.visualstudio.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.7,
    ],
    [
        'name' => 'Adobe Photoshop',
        'image_url' => 'https://loghi-famosi.com/wp-content/uploads/2021/01/Adobe-Photoshop-Logo.png',
        'description' => 'Software di fotoritocco',
        'category' => 'Grafica',
        'release_year' => 1990,
        'latest_version' => '2022',
        'download_link' => 'https://www.adobe.com/products/photoshop.html',
        'supported_os' => 'Windows, macOS',
        'vote' => 4.5,
    ],
    [
        'name' => 'Google Chrome',
        'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Chrome_icon_(September_2014).svg/150px-Google_Chrome_icon_(September_2014).svg.png',
        'description' => 'Browser web sviluppato da Google',
        'category' => 'Browser web',
        'release_year' => 2008,
        'latest_version' => '98.0.4758.102',
        'download_link' => 'https://www.google.com/chrome/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.8,
    ],
    [
        'name' => 'GitHub',
        'image_url' => 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
        'description' => 'Piattaforma di sviluppo collaborativo di software',
        'category' => 'Collaborazione',
        'release_year' => 2008,
        'latest_version' => null,
        'download_link' => 'https://github.com/',
        'supported_os' => 'Web',
        'vote' => 4.9,
    ],
    [
        'name' => 'MySQL',
        'image_url' => 'https://www.vectorlogo.zone/logos/mysql/mysql-ar21.png',
        'description' => 'Sistema di gestione di database relazionali',
        'category' => 'Database',
        'release_year' => 1995,
        'latest_version' => '8.0.28',
        'download_link' => 'https://www.mysql.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.6,
    ],
    [
        'name' => 'Node.js',
        'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Node.js_logo_2015.svg/2560px-Node.js_logo_2015.svg.png',
        'description' => 'Runtime di JavaScript basato su Chrome V8',
        'category' => 'Runtime di JavaScript',
        'release_year' => 2009,
        'latest_version' => '16.14.0',
        'download_link' => 'https://nodejs.org/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.5,
    ],
    [
        'name' => 'Sublime Text',
        'image_url' => 'https://www.schemecolor.com/wp-content/uploads/sublime-text-logo.png',
        'description' => 'Editor di codice leggero e veloce',
        'category' => 'Editor di codice',
        'release_year' => 2008,
        'latest_version' => '4.1.5',
        'download_link' => 'https://www.sublimetext.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.8,
    ],
    [
        'name' => 'Notepad++',
        'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Notepad%2B%2B_Logo.svg/2367px-Notepad%2B%2B_Logo.svg.png',
        'description' => 'Editor di codice open source per Windows',
        'category' => 'Editor di codice',
        'release_year' => 2003,
        'latest_version' => '8.3.2',
        'download_link' => 'https://notepad-plus-plus.org/',
        'supported_os' => 'Windows',
        'vote' => 4.7,
    ],
    [
        'name' => 'Postman',
        'image_url' => 'https://blog.postman.com/wp-content/uploads/2014/07/logo.png',
        'description' => 'Client RESTful API',
        'category' => 'API',
        'release_year' => 2012,
        'latest_version' => '9.1.5',
        'download_link' => 'https://www.postman.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.9,
    ],
    [
        'name' => 'MongoDB',
        'image_url' => 'https://cyclr.com/wp-content/uploads/2022/03/ext-553.png',
        'description' => 'Database non relazionale basato su documenti',
        'category' => 'Database',
        'release_year' => 2009,
        'latest_version' => '5.1.1',
        'download_link' => 'https://www.mongodb.com/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.7,
    ],
    [
        'name' => 'Atom',
        'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Atom_editor_logo.svg/1024px-Atom_editor_logo.svg.png',
        'description' => 'Editor di codice open source',
        'category' => 'Editor di codice',
        'release_year' => 2014,
        'latest_version' => '1.54.0',
        'download_link' => 'https://atom.io/',
        'supported_os' => 'Windows, macOS, Linux',
        'vote' => 4.6,
    ],
    [
        'name' => 'React',
        'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1024px-React-icon.svg.png',
        'description' => 'Libreria JavaScript per lo sviluppo di interfacce utente',
        'category' => 'Libreria JavaScript',
        'release_year' => 2013,
        'latest_version' => '18.0.3',
        'download_link' => 'https://reactjs.org/',
        'supported_os' => 'Web',
        'vote' => 4.7,
    ]
];
